# Generated by Django 5.0.4 on 2024-05-08 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_p', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('Des_product', models.CharField(blank=True, max_length=200, null=True)),
                ('Img_product', models.ImageField(blank=True, null=True, upload_to='CategoryImages')),
            ],
        ),
    ]
