# Generated by Django 5.0.4 on 2024-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_productdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='Img_product',
            field=models.ImageField(blank=True, null=True, upload_to='ProductImages'),
        ),
    ]
